server:
  port: "8080"
  address: ""
  network: "tcp"
telegramBot:
  token: ""
availableServices:
  mail_names: ["imap.gmail.com:993", "imap.yandex.ru:993"]
httpServer:
  network: "tcp"
  address: "8081"
